#!/usr/bin/env node
/**
 * dev-link.mjs
 *
 * Installs a global `fidelios` command that runs the CLI via tsx from this
 * monorepo. Designed for local development — use this instead of
 * `npm install -g fidelios`.
 *
 * Usage:
 *   pnpm dev:link
 *   node scripts/dev-link.mjs
 */

import { writeFileSync, chmodSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import os from "node:os";
import { execSync } from "node:child_process";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tsxBin = resolve(repoRoot, "cli/node_modules/.bin/tsx");
const cliSrc = resolve(repoRoot, "cli/src/index.ts");

if (!existsSync(tsxBin)) {
  console.error(`tsx not found at: ${tsxBin}`);
  console.error("Run 'pnpm install' first.");
  process.exit(1);
}

if (!existsSync(cliSrc)) {
  console.error(`CLI source not found at: ${cliSrc}`);
  process.exit(1);
}

// Find a writable bin directory present in PATH
const pathDirs = (process.env.PATH ?? "").split(":");
const candidates = [
  "/opt/homebrew/bin",
  "/usr/local/bin",
  resolve(os.homedir(), ".local/bin"),
];

let binDir = null;
for (const candidate of candidates) {
  if (!existsSync(candidate)) continue;
  if (!pathDirs.includes(candidate)) continue;
  try {
    execSync(`test -w "${candidate}"`, { stdio: "ignore" });
    binDir = candidate;
    break;
  } catch {
    // not writable — try next
  }
}

if (!binDir) {
  console.error("Could not find a writable bin directory in PATH.");
  console.error("Tried: " + candidates.join(", "));
  console.error("");
  console.error("To fix, either:");
  console.error("  1. Add ~/.local/bin to your PATH, then run again.");
  console.error("  2. Run with sudo: sudo node scripts/dev-link.mjs");
  process.exit(1);
}

const wrapper = `#!/bin/bash
# FideliOS development CLI — generated by: pnpm dev:link
# Runs the CLI from monorepo source via tsx (TypeScript).
# Repo: ${repoRoot}
exec "${tsxBin}" "${cliSrc}" "$@"
`;

const target = resolve(binDir, "fidelios");
writeFileSync(target, wrapper, "utf8");
chmodSync(target, 0o755);

console.log(`✓ Installed: ${target}`);
console.log(`  tsx:       ${tsxBin}`);
console.log(`  CLI:       ${cliSrc}`);
console.log("");
console.log("Run:  fidelios run");
console.log("      fidelios --help");
